language: node_js
node_js:
- '7'
before_install:
- openssl aes-256-cbc -K $encrypted_13177b82e83b_key -iv $encrypted_13177b82e83b_iv -in secrets.enc -out id_rsa -d
- chmod 600 id_rsa
- cp id_rsa ~/.ssh/id_rsa
before_script:
- npm install -g gulp
script:
- gulp
- bash deploy
